"""first

Revision ID: 1eb5e55024b3
Revises: 8ac26e2c0e73
Create Date: 2022-03-03 16:23:48.305165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb5e55024b3'
down_revision = '8ac26e2c0e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_in_game',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_in_game_id'), 'stock_in_game', ['id'], unique=False)
    op.create_index(op.f('ix_stock_in_game_symbol'), 'stock_in_game', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_in_game_symbol'), table_name='stock_in_game')
    op.drop_index(op.f('ix_stock_in_game_id'), table_name='stock_in_game')
    op.drop_table('stock_in_game')
    # ### end Alembic commands ###
