"""Do update

Revision ID: 3640a8c81600
Revises: e47d95cdb50a
Create Date: 2022-03-07 13:14:21.109601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3640a8c81600'
down_revision = 'e47d95cdb50a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
