"""Points int -> float

Revision ID: 4f275edde571
Revises: 3640a8c81600
Create Date: 2022-03-07 16:25:23.666766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f275edde571'
down_revision = '3640a8c81600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
