"""Points int -> float

Revision ID: 50a5c230fae1
Revises: 4f275edde571
Create Date: 2022-03-07 17:07:32.701627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a5c230fae1'
down_revision = '4f275edde571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
