"""diff int->float

Revision ID: 7153e96f0f2e
Revises: ce18a32e3f78
Create Date: 2022-03-09 16:51:23.702226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7153e96f0f2e'
down_revision = 'ce18a32e3f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
