"""first

Revision ID: 8ac26e2c0e73
Revises: eef71ea82f59
Create Date: 2022-03-03 16:21:51.906540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac26e2c0e73'
down_revision = 'eef71ea82f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
