"""first

Revision ID: 9da6aaede675
Revises: 1eb5e55024b3
Create Date: 2022-03-03 16:24:26.113061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da6aaede675'
down_revision = '1eb5e55024b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
