"""Points int -> float

Revision ID: ce18a32e3f78
Revises: 50a5c230fae1
Create Date: 2022-03-07 17:13:16.697176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce18a32e3f78'
down_revision = '50a5c230fae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
