"""first

Revision ID: d234474e4425
Revises: e109301ea260
Create Date: 2022-03-04 13:01:56.531951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd234474e4425'
down_revision = 'e109301ea260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stock_in_game', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_in_game', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stock', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
