"""first

Revision ID: e109301ea260
Revises: bbe48304e90b
Create Date: 2022-03-04 11:27:30.635143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e109301ea260'
down_revision = 'bbe48304e90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
