"""first

Revision ID: eef71ea82f59
Revises: 3ecc730a27d9
Create Date: 2022-03-03 16:02:43.484439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef71ea82f59'
down_revision = '3ecc730a27d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
