server:
  port: $PORT
admin:
  email: $ADMIN_EMAIL
  password: $ADMIN_PASS
database:
  host: $DB_HOST
  port: $DB_PORT
  user: $DB_USER
  password: $DB_PASS
  database:  $DB_NAME
bot:
  token:  $BOT_TOKEN
  group_id: $GROUP_ID


